/**
 * Injected at build time from .env / Cloudflare env vars.
 */
window.VG_SUPABASE_URL = "__SUPABASE_URL__";
window.VG_SUPABASE_ANON_KEY = "__SUPABASE_ANON_KEY__";
window.VG_GOOGLE_WEB_CLIENT_ID = "__GOOGLE_WEB_CLIENT_ID__";
window.VG_POLAR_CHECKOUT_LINK_ANNUAL = "__POLAR_CHECKOUT_LINK_ANNUAL__";
window.VG_POLAR_CHECKOUT_LINK_PRO_WEEKLY = "__POLAR_CHECKOUT_LINK_PRO_WEEKLY__";
